Repository NASA-AMMOS/aerie, pull requests merged in 2022-11, with the labels that each got.

#412 docs: update readme
  README.md
Labels: documentation

#413 build: remove jheaps and jgrapht from third-party
  scheduler-driver/build.gradle
  third-party/jgrapht-core-1.5.1.jar
  third-party/jheaps-0.13.jar
Labels: build

#414 docs: update readme
  README.md
Labels: documentation

#415 [AERIE-2155] Use version for publishing only
  build.gradle
  contrib/build.gradle
  examples/banananation/build.gradle
  merlin-driver/build.gradle
  merlin-framework-junit/build.gradle
  merlin-framework-processor/build.gradle
  merlin-framework/build.gradle
  merlin-sdk/build.gradle
  parsing-utilities/build.gradle
Labels: build

#399 [AERIE-2175] Plan Merging
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  deployment/hasura/metadata/databases/AerieMerlin/functions/functions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_conflicting_activities.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_merge_request.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_merge_request_comment.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_merge_staging_area.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan_snapshot.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan_snapshot_activities.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  docs/source/graphql-api/examples.md
  merlin-server/sql/merlin/hasura_functions.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/merge_comments.sql
  merlin-server/sql/merlin/merge_request.sql
  merlin-server/sql/merlin/plan_merge.sql
  merlin-server/sql/merlin/tables/activity_directive.sql
  merlin-server/sql/merlin/tables/activity_directive_validations.sql
  merlin-server/sql/merlin/tables/plan.sql
Labels: feature

#402 [AERIE-2141] Add during expression by updating ForEach and Spans
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Spans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ActivitySpan.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ForEachActivitySpans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ForEachActivityViolations.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ViolationsOfWindows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/WindowsFromSpans.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsersTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/time/SpansTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/constraints-dsl-compiler/src/libs/mission-model-generated-code.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
Labels: feature

#411 Wrap simulation results writing in TransactionContext
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
Labels: performance

#416 [FIX] Use property for publishing version string
  build.gradle
  contrib/build.gradle
  examples/banananation/build.gradle
  gradle.properties
  merlin-driver/build.gradle
  merlin-framework-junit/build.gradle
  merlin-framework-processor/build.gradle
  merlin-framework/build.gradle
  merlin-sdk/build.gradle
  parsing-utilities/build.gradle
Labels: hotfix

#418 [HOTFIX] Put `setProperty()` in `configure` block
  build.gradle
Labels: hotfix

#421 [AERIE-2180] Constraints docs
  docs/Makefile
  docs/buildExternalDocs.bash
  docs/old_site/activity-plans/scheduling-guide.rst
  docs/old_site/constraints/index.rst
  docs/poetry.lock
  docs/source/user-guide/ui-api-guide/constraints/authoring-constraints.rst
  docs/source/user-guide/ui-api-guide/constraints/check-constraints.rst
  docs/source/user-guide/ui-api-guide/constraints/examples.md
  docs/source/user-guide/ui-api-guide/constraints/index.rst
  docs/source/user-guide/ui-api-guide/constraints/writing-constraints.rst
  docs/sphinx_scylladb_theme/footer.html
  docs/sphinx_scylladb_theme/header.html
Labels: documentation

#397 [AERIE-2145] Gaps in external profiles
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfile.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfileTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileTest.java
  docs/source/user-guide/ui-api-guide/external-datasets/index.rst
  docs/source/user-guide/ui-api-guide/external-datasets/managing.md
  docs/source/user-guide/ui-api-guide/external-datasets/usage-constraints.md
  docs/source/user-guide/ui-api-guide/external-resource-profiles/examples.md
  docs/source/user-guide/ui-api-guide/external-resource-profiles/index.rst
  docs/source/user-guide/ui-api-guide/index.rst
  e2e-tests/src/tests/external-datasets.test.ts
  e2e-tests/src/types/external-dataset.d.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/Duration.java
  merlin-server/sql/merlin/tables/profile.sql
  merlin-server/sql/merlin/tables/profile_segment.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ProfileParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/DiscreteProfile.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ProfileSet.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/RealProfile.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PreparedStatements.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ProfileRecord.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ProfileRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  parsing-utilities/src/main/java/gov/nasa/jpl/aerie/json/BasicParsers.java
Labels: feature

#424 [FIX] Load scheduling DSL TypeScript libraries in `scheduler-server`
  e2e-tests/src/tests/scheduler.test.ts
  e2e-tests/src/types/scheduling-goal.d.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  scheduler-server/build.gradle
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GenerateSchedulingLibAction.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/GenerateSchedulingLibActionTest.java
Labels: fix

#423 [REFACTOR] Avoid computing samples eagerly in SimulationResults
  examples/banananation/src/test/java/gov/nasa/jpl/aerie/banananation/Main.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimulateMapSchedule.java
  examples/foo-missionmodel/src/test/resources/gov/nasa/jpl/aerie/foomissionmodel/plan.json
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResults.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
Labels: refactor

#339 [AERIE-2115] Use IntervalMap for Linear and Discrete Profiles
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfilePiece.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearEquation.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfilePiece.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/Profile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/IntervalMap.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Windows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Changes.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/DiscreteParameter.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/DiscreteValue.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Equal.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/GreaterThan.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/GreaterThanOrEqual.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/LessThan.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/LessThanOrEqual.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/NotEqual.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/RealParameter.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/RealResource.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/RealValue.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Transition.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfileTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfileTimeDomainTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileBenchmark.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileTimeDomainTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/TimeRangeExpression.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/resources/StateQueryParam.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationResultsConverter.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestFilters.java
Labels: refactor

#419 [AERIE-2205] Rename condition table to "constraint"
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_constraint.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  e2e-tests/src/utilities/gql.ts
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/tables/constraint.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetModelConstraintsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetPlanConstraintsAction.java
Labels: breaking change, refactor

#437 docs: remove redundant env docs
  docs/source/contribute/quickstart/environment.md
  docs/source/contribute/quickstart/index.rst
  docs/source/user-guide/quickstart/environment.md
  docs/source/user-guide/quickstart/index.rst
Labels: documentation

#410 [AERIE-2142] Global scheduling condition in scheduling eDSL + mutex
  docs/buildExternalDocs.bash
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/ActivityTypeList.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingCondition.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/GlobalSchedulingConditionRecord.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/SchedulingDSL.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/PostgresSpecificationRepository.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationService.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationServiceTest.java
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-ast.ts
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationService.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: breaking change, feature

#448 [HOTFIX] Fix broken links in Docs
  docs/source/contribute/guidelines/CODE_OF_CONDUCT.md
  docs/source/user-guide/ui-api-guide/constraints/index.rst
  docs/source/user-guide/ui-api-guide/constraints/writing-constraints.md
Labels: documentation, hotfix

#456 docs: Reference `api-examples`
  docs/source/user-guide/ui-api-guide/api-examples.md
  docs/source/user-guide/ui-api-guide/api-examples.rst
  docs/source/user-guide/ui-api-guide/constraints/index.rst
  docs/source/user-guide/ui-api-guide/external-datasets/managing.md
  docs/source/user-guide/ui-api-guide/sequence-editor/index.rst
Labels: documentation

#438 [AERIE 2131] Database Migration Script
  deployment/aerie_db_migration
  deployment/config.yaml
  deployment/hasura/config.yaml
  deployment/sample_migrations/config.yaml
  deployment/sample_migrations/migrations/AerieCommanding/1664478381304_rename_mission_column/down.sql
  deployment/sample_migrations/migrations/AerieCommanding/1664478381304_rename_mission_column/up.sql
  deployment/sample_migrations/migrations/AerieCommanding/1664478481307_add_column_expand_to/down.sql
  deployment/sample_migrations/migrations/AerieCommanding/1664478481307_add_column_expand_to/up.sql
  deployment/sample_migrations/migrations/AerieMerlin/1667319761264_test_migration/down.sql
  deployment/sample_migrations/migrations/AerieMerlin/1667319761264_test_migration/up.sql
  docs/source/user-guide/upgrade-guides/db_migration_assistant.md
  docs/source/user-guide/upgrade-guides/index.rst
Labels: ci

#433 [AERIE-2198] Assign Gaps
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/Profile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Windows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/AssignGaps.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/WindowsValue.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsersTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
Labels: feature

#468 docs: add GitHub release.yml
  .github/release.yml
Labels: documentation

#472 Include MD link on Examples/index.rst
  docs/source/contribute/documentation/examples/index.rst
Labels: documentation

#465 [AERIE-2187] Documentation: activity types and configuration
  docs/source/user-guide/mission-modeler-guide/activity-types/activity-parameters.md
  docs/source/user-guide/mission-modeler-guide/activity-types/activity-parameters.rst
  docs/source/user-guide/mission-modeler-guide/activity-types/effect-model.md
  docs/source/user-guide/mission-modeler-guide/activity-types/effect-model.rst
  docs/source/user-guide/mission-modeler-guide/activity-types/index.rst
  docs/source/user-guide/mission-modeler-guide/configuration/configuration-parameters.md
  docs/source/user-guide/mission-modeler-guide/configuration/declaration.md
  docs/source/user-guide/mission-modeler-guide/configuration/examples.md
  docs/source/user-guide/mission-modeler-guide/configuration/examples.rst
  docs/source/user-guide/mission-modeler-guide/configuration/index.rst
  docs/source/user-guide/mission-modeler-guide/configuration/parameter-file-input-config.rst
  docs/source/user-guide/mission-modeler-guide/configuration/simulation-configuration.rst
  docs/source/user-guide/mission-modeler-guide/index.rst
  docs/source/user-guide/mission-modeler-guide/parameters/export-parameter.md
  docs/source/user-guide/mission-modeler-guide/parameters/export-template.md
  docs/source/user-guide/mission-modeler-guide/parameters/export-with-defaults.md
  docs/source/user-guide/mission-modeler-guide/parameters/index.rst
  docs/source/user-guide/mission-modeler-guide/parameters/without-export.md
Labels: documentation

#474 Use aerie logo with background in readme
  README.md
  docs/sphinx_scylladb_theme/static/img/logos/aerie-wordmark-with-background.svg
Labels: documentation

#382 Move the simulation thread pool from the model to the driver
  docs/old_site/mission-modeling/activity-mappers.md
  examples/config-with-defaults/src/test/java/gov/nasa/jpl/aerie/configwithdefaults/ConfigurationTest.java
  examples/config-without-defaults/src/test/java/gov/nasa/jpl/aerie/configwithoutdefaults/ConfigurationTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/FooActivityTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/MissionConfigurationTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimpleDataTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimulateMapSchedule.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/MissionModel.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/MissionModelBuilder.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-framework-junit/src/main/java/gov/nasa/jpl/aerie/merlin/framework/junit/MerlinExtension.java
  merlin-framework-junit/src/main/java/gov/nasa/jpl/aerie/merlin/framework/junit/MerlinTestContext.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/generator/MissionModelGenerator.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ActivityMapper.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/Context.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/InitializationContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ModelActions.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/QueryContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ReplayingReactionContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ReplayingTask.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/RootModel.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/TaskHandle.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ThreadedReactionContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ThreadedTask.java
  merlin-framework/src/test/java/gov/nasa/jpl/aerie/merlin/framework/ThreadedTaskTest.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/Initializer.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/Scheduler.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/DirectiveType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/TaskFactory.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/TaskStatus.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationDriver.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/SimulationUtility.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationTest.java
  scheduler-driver/src/test/resources/gov/nasa/jpl/aerie/scheduler/aerielander.jar
Labels: breaking change, refactor

#476 Update documentation about scheduling
  docs/source/user-guide/ui-api-guide/scheduling/img/click-analysis-scheduling-panel.png
  docs/source/user-guide/ui-api-guide/scheduling/img/click-scheduling-scheduling-panel.png
  docs/source/user-guide/ui-api-guide/scheduling/img/failure.png
  docs/source/user-guide/ui-api-guide/scheduling/img/goal-editor-new.png
  docs/source/user-guide/ui-api-guide/scheduling/img/goal-editor.png
  docs/source/user-guide/ui-api-guide/scheduling/img/open-scheduling-pane.png
  docs/source/user-guide/ui-api-guide/scheduling/img/right-click-goal.png
  docs/source/user-guide/ui-api-guide/scheduling/img/scheduling-error.png
  docs/source/user-guide/ui-api-guide/scheduling/img/scheduling-failed.png
  docs/source/user-guide/ui-api-guide/scheduling/img/scheduling-panel.png
  docs/source/user-guide/ui-api-guide/scheduling/img/scheduling-specification.png
  docs/source/user-guide/ui-api-guide/scheduling/img/scheduling-success.png
  docs/source/user-guide/ui-api-guide/scheduling/img/success.png
  docs/source/user-guide/ui-api-guide/scheduling/index.rst
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-conditions.rst
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-create-delete.rst
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-goals.rst
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-specification.rst
Labels: documentation

#479 Remove Scylla links
  docs/source/contribute/documentation/examples/admonitions.rst
  docs/source/contribute/documentation/examples/links.rst
  docs/source/contribute/documentation/examples/tabs.rst
  docs/source/contribute/documentation/examples/topic-box.rst
Labels: documentation, hotfix

#478 [AERIE-2188] Mission modeling docs updates
  docs/old_site/background.rst
  docs/old_site/mission-modeling/models-and-resources.md
  docs/old_site/mission-modeling/value-schemas.md
  docs/source/user-guide/mission-modeler-guide/activity-mappers/activity-mapper-interface.rst
  docs/source/user-guide/mission-modeler-guide/activity-mappers/example-activity-mapper.rst
  docs/source/user-guide/mission-modeler-guide/activity-mappers/index.rst
  docs/source/user-guide/mission-modeler-guide/activity-types/effect-model.md
  docs/source/user-guide/mission-modeler-guide/custom-value-types/examples-value-schema.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/index.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/serialized-value-schemas.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/value-schema-basics.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/value-schema-declaration.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/value-schema-generation.rst
  docs/source/user-guide/mission-modeler-guide/custom-value-types/value-schema-in-code.rst
  docs/source/user-guide/mission-modeler-guide/foundations-of-simulation-and-modeling.rst
  docs/source/user-guide/mission-modeler-guide/index.rst
  docs/source/user-guide/mission-modeler-guide/resources-and-models/custom-models.rst
  docs/source/user-guide/mission-modeler-guide/resources-and-models/derived-resources.rst
  docs/source/user-guide/mission-modeler-guide/resources-and-models/index.rst
  docs/source/user-guide/mission-modeler-guide/resources-and-models/sampled-resources.rst
  docs/source/user-guide/quickstart/create-mission-model.rst
Labels: documentation

#482 Move more documents from old_site to main
  README.md
  docs/old_site/constraints/overview.md
  docs/old_site/contribute/contribute-docs.rst
  docs/old_site/contribute/index.rst
  docs/old_site/deployment/aws-deployment.md
  docs/old_site/deployment/index.rst
  docs/old_site/examples/admonitions.rst
  docs/old_site/examples/code-blocks.rst
  docs/old_site/examples/collapse.rst
  docs/old_site/examples/glossary.rst
  docs/old_site/examples/headings.rst
  docs/old_site/examples/hero-box.rst
  docs/old_site/examples/images.rst
  docs/old_site/examples/images/checkmark.png
  docs/old_site/examples/images/diagram.svg
  docs/old_site/examples/includes.rst
  docs/old_site/examples/index.rst
  docs/old_site/examples/links.rst
  docs/old_site/examples/lists.rst
  docs/old_site/examples/panel-box.rst
  docs/old_site/examples/substitutions.rst
  docs/old_site/examples/tables.rst
  docs/old_site/examples/tabs.rst
  docs/old_site/examples/text.rst
  docs/old_site/examples/toc.rst
  docs/old_site/examples/topic-box.rst
  docs/old_site/examples/versions.rst
  docs/old_site/graphql-api/examples.md
  docs/old_site/graphql-api/index.rst
  docs/old_site/index.rst
  docs/old_site/user-interface/index.rst
  docs/old_site/user-interface/planning.md
  docs/source/contribute/guidelines/CODE_OF_CONDUCT.md
  docs/source/contribute/guidelines/CONTRIBUTING.md
  docs/source/contribute/guidelines/conventions.md
  docs/source/contribute/guidelines/index.rst
  docs/source/contribute/index.rst
  docs/source/contribute/quickstart/index.rst
  docs/source/user-guide/mission-modeler-guide/activity-mappers/activity-mapper-interface.rst
  docs/source/user-guide/mission-modeler-guide/index.rst
  docs/source/user-guide/quickstart/index.rst
  docs/source/user-guide/tutorials/activity-directive-metadata.md
  docs/source/user-guide/tutorials/index.rst
  docs/source/user-guide/tutorials/ui-custom-base-path.md
  docs/source/user-guide/ui-api-guide/constraints/examples.md
  docs/source/user-guide/ui-api-guide/constraints/writing-constraints.md
  docs/source/user-guide/ui-api-guide/ui-layouts/external-web-apps.rst
  docs/source/user-guide/ui-api-guide/ui-layouts/index.rst
  docs/source/user-guide/ui-api-guide/ui-layouts/ui-views.md
  docs/source/user-guide/ui-api-guide/ui-layouts/ui-views.rst
Labels: documentation

#436 Release Version 1.0.0
  docs/source/conf.py
  docs/source/user-guide/tutorials/ui-custom-base-path.md
  docs/source/user-guide/upgrade-guides/0-13-2-to-1-0-0.md
  docs/source/user-guide/upgrade-guides/index.rst
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#483 Update scheduling goal examples to use Temporal.Duration
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
Labels: documentation

#485 Update command expansion docs
  docs/source/user-guide/ui-api-guide/command-expansion/expansion-logic.rst
  docs/source/user-guide/ui-api-guide/command-expansion/expansion-set.rst
  docs/source/user-guide/ui-api-guide/command-expansion/index.rst
  docs/source/user-guide/ui-api-guide/command-expansion/sequences.rst
  docs/source/user-guide/ui-api-guide/command-expansion/trigger-command-expansion.rst
  docs/source/user-guide/ui-api-guide/images/cmdexp_args_list.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_author.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_author_set.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_commands_list.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_declare_seqid.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_logic_edit_delete.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_logic_filter.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_manage_logic.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_nav_plan_exp.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_new_logic.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_open_seq.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_props.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_props_args.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_set.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_trigger.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_uploadCMD.png
  docs/source/user-guide/ui-api-guide/images/cmdexp_workflow.png
  docs/source/user-guide/ui-api-guide/images/home_topmenu.png
Labels: documentation

#486 Fix broken links in Docs
  docs/source/user-guide/mission-modeler-guide/activity-mappers/activity-mapper-interface.rst
  docs/source/user-guide/mission-modeler-guide/index.rst
  docs/source/user-guide/ui-api-guide/constraints/writing-constraints.md
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-conditions.rst
  docs/source/user-guide/ui-api-guide/scheduling/scheduling-goals.rst
Labels: documentation

#434 Use a record instead of a pair for profile segments
  constraints/build.gradle
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfile.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfileTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimulateMapSchedule.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResults.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/ProfileSegment.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-driver/src/test/java/gov/nasa/jpl/aerie/merlin/driver/CellExpiryTest.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ProfileParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/DiscreteProfile.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ProfileSet.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/RealProfile.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ProfileRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationTest.java
Labels: refactor

#492 Updated the hausra and postgres container names with the aerie prefix
  docker-compose.yml
Labels: build

#487 Add external dataset CSV example
  docs/source/user-guide/ui-api-guide/api-examples.rst
  docs/source/user-guide/ui-api-guide/external-datasets/managing.md
Labels: documentation

#495 Add standalone Aerie Docker images
  .dockerignore
  .github/workflows/publish.yml
  README.md
  docker/Dockerfile.hasura
  docker/Dockerfile.postgres
  docker/README.md
Labels: ci

#497 Provide Markdown Syntax in Documentation Examples
  docs/poetry.lock
  docs/source/aerie-glossary.md
  docs/source/conf.py
  docs/source/contribute/documentation/docs-pr.rst
  docs/source/contribute/documentation/examples/admonitions.md
  docs/source/contribute/documentation/examples/admonitions.rst
  docs/source/contribute/documentation/examples/code-blocks.md
  docs/source/contribute/documentation/examples/code-blocks.rst
  docs/source/contribute/documentation/examples/collapse.md
  docs/source/contribute/documentation/examples/collapse.rst
  docs/source/contribute/documentation/examples/eval-rst.md
  docs/source/contribute/documentation/examples/glossary.md
  docs/source/contribute/documentation/examples/glossary.rst
  docs/source/contribute/documentation/examples/headings.md
  docs/source/contribute/documentation/examples/headings.rst
  docs/source/contribute/documentation/examples/hero-box.md
  docs/source/contribute/documentation/examples/hero-box.rst
  docs/source/contribute/documentation/examples/images.md
  docs/source/contribute/documentation/examples/images.rst
  docs/source/contribute/documentation/examples/include.md
  docs/source/contribute/documentation/examples/includes.rst
  docs/source/contribute/documentation/examples/index.rst
  docs/source/contribute/documentation/examples/links.rst
  docs/source/contribute/documentation/examples/lists.md
  docs/source/contribute/documentation/examples/lists.rst
  docs/source/contribute/documentation/examples/panel-box.rst
  docs/source/contribute/documentation/examples/substitutions.md
  docs/source/contribute/documentation/examples/substitutions.rst
  docs/source/contribute/documentation/examples/tables.md
  docs/source/contribute/documentation/examples/tables.rst
  docs/source/contribute/documentation/examples/tabs.md
  docs/source/contribute/documentation/examples/tabs.rst
  docs/source/contribute/documentation/examples/text.md
  docs/source/contribute/documentation/examples/text.rst
  docs/source/contribute/documentation/examples/toc.md
  docs/source/contribute/documentation/examples/toc.rst
  docs/source/contribute/documentation/examples/topic-box.md
  docs/source/contribute/documentation/examples/topic-box.rst
  docs/source/contribute/documentation/examples/versions.md
  docs/source/contribute/documentation/examples/versions.rst
  docs/source/contribute/documentation/index.rst
  docs/source/contribute/documentation/writer-handbook.rst
  docs/sphinx_scylladb_theme/__init__.py
  docs/sphinx_scylladb_theme/extensions/panel_box.py
Labels: documentation
