Repository NASA-AMMOS/aerie, pull requests merged in 2022-10, with the labels that each got.

#355 Add logo and favicon to docs
  docs/poetry.lock
  docs/sphinx_scylladb_theme/404.html
  docs/sphinx_scylladb_theme/footer.html
  docs/sphinx_scylladb_theme/header.html
  docs/sphinx_scylladb_theme/layout.html
  docs/sphinx_scylladb_theme/static/css/main.css
  docs/sphinx_scylladb_theme/static/img/logos/aerie-logo-dark.svg
  docs/sphinx_scylladb_theme/static/img/logos/aerie-logo-light.svg
  docs/sphinx_scylladb_theme/static/img/logos/favicon.ico
  docs/sphinx_scylladb_theme/static/img/logos/favicon.svg
Labels: documentation

#356 [DOCS] Track git tag 0.13.1
  docs/source/conf.py
Labels: documentation

#357 [DOCS] Set the latest version
  docs/source/conf.py
Labels: documentation

#358 docs: various updates
  .github/workflows/docs-pages.yaml
  docs/source/activity-plans/images/fig-1.png
  docs/source/activity-plans/images/fig-2.png
  docs/source/activity-plans/images/fig-3.png
  docs/source/activity-plans/images/fig-4.1.png
  docs/source/activity-plans/images/fig-4.2.png
  docs/source/activity-plans/images/fig-4.png
  docs/source/activity-plans/images/fig-5.png
  docs/source/activity-plans/images/fig-6.png
  docs/source/activity-plans/index.rst
  docs/source/activity-plans/merlin-activity-plans.md
  docs/source/activity-plans/planning-ui.md
  docs/source/activity-plans/precomputed-profiles.md
  docs/source/activity-plans/simulation-configuration.md
  docs/source/activity-plans/simulation-results.md
  docs/source/aerie-api/aerie-graphql-api.md
  docs/source/aerie-glossary.md
  docs/source/command-expansion/create-an-expansion-set.md
  docs/source/command-expansion/create-sequence.md
  docs/source/command-expansion/expand-the-plan.md
  docs/source/command-expansion/expansion-authoring-ide-setup.md
  docs/source/command-expansion/expansion-logic-api.md
  docs/source/command-expansion/generate-activity-typescript-library.md
  docs/source/command-expansion/generate-seqjson-from-a-standalone-sequence.md
  docs/source/command-expansion/get-expanded-commands.md
  docs/source/command-expansion/index.rst
  docs/source/command-expansion/link-simulated-activity-to-sequence.md
  docs/source/command-expansion/retrieve-seqjson-serialization-of-sequence.md
  docs/source/command-expansion/submit-expansion-logic.md
  docs/source/command-expansion/upload-and-generate-command-library-file.md
  docs/source/command-expansion/valid-sequence-json-format.md
  docs/source/constraints/images/sim-config-args.png
  docs/source/constraints/images/sim-config-plans.png
  docs/source/constraints/index.rst
  docs/source/constraints/overview.md
  docs/source/graphql-api/examples.md
  docs/source/graphql-api/index.rst
  docs/source/graphql-api/overview.md
  docs/source/images/ConstraintUI.png
  docs/source/images/fig-10.png
  docs/source/images/fig-2.png
  docs/source/images/fig-3.png
  docs/source/images/fig-4.1.png
  docs/source/images/fig-4.2.png
  docs/source/images/fig-4.png
  docs/source/images/fig-5.png
  docs/source/images/fig-6.png
  docs/source/images/fig-7.png
  docs/source/images/fig-8.png
  docs/source/images/fig-9.png
  docs/source/images/sim-config-args.png
  docs/source/images/sim-config-plans.png
  docs/source/index.rst
  docs/source/upgrade-guides/index.rst
  docs/source/upgrade/0-12-3-to-0-13-0.md
  docs/source/upgrade/index.rst
  docs/source/user-interface/activity-directive-metadata.md
  docs/source/user-interface/index.rst
  docs/source/user-interface/planning.md
  docs/source/user-interface/views.md
Labels: documentation

#361 [DOCS] 0.13.1 upgrade instructions
  docs/source/mission-modeling/index.rst
  docs/source/mission-modeling/models-and-resources.md
  docs/source/upgrade-guides/0-13-0-to-0-13-1.rst
  docs/source/upgrade-guides/index.rst
Labels: documentation

#370 [AERIE-2153] Remove `refreshActivityValidations` event trigger
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_directive.yaml
Labels: hotfix

#373 [HOTFIX] Constraints Any semantics should preserve false
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/All.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Any.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ViolationsOf.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
Labels: hotfix

#381 docs: update ui custom base path
  docs/source/deployment/ui-custom-base-path.md
Labels: documentation

#384 build: update gradle wrapper version
  .github/workflows/codeql.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  docs/source/deployment/building.md
  gradle/wrapper/gradle-wrapper.properties
Labels: hotfix

#385 [DOCS] fix link in README
  README.md
Labels: documentation

#387 fix: update activity table to use start_time_doy
  deployment/postgres-init-db/data/ui/views/example_0.json
Labels: hotfix

#386 [AERIE-2178] Update 0.13.2 migration docs
  docs/release-checklist.md
  docs/source/mission-modeling/activities.md
  docs/source/upgrade-guides/0-13-1-to-0-13-2.rst
  docs/source/upgrade-guides/index.rst
Labels: documentation

#388 [DOCS] Fix link and remove outdated waitFor() docs
  docs/source/mission-modeling/activities.md
  docs/source/upgrade-guides/0-13-1-to-0-13-2.rst
Labels: documentation

#389 [HOTFIX] Change the Merlin Worker Java image from alpine to jammy
  merlin-worker/Dockerfile
Labels: hotfix

#390 Revert "[FEAT](AERIE-2146) Include EDSL API docs in docs"
  .github/workflows/docs-pages.yaml
  .github/workflows/docs-pr.yml
  docs/poetry.lock
  docs/source/_ext/rst_jinja.py
  docs/source/activity-plans/scheduling-guide.rst
  docs/source/conf.py
  docs/source/constraints/overview.md
  docs/source/edsl-api-documentation/index.rst
  docs/source/index.rst
  merlin-server/build.gradle
  merlin-server/constraints-dsl-compiler/package-lock.json
  merlin-server/constraints-dsl-compiler/package.json
  scheduler-server/build.gradle
  scheduler-server/scheduling-dsl-compiler/package-lock.json
  scheduler-server/scheduling-dsl-compiler/package.json
  scheduler-server/scheduling-dsl-compiler/tsconfig.json
Labels: hotfix

#393 docs: fix v0.13.2 tag
  docs/source/conf.py
Labels: documentation

#403 refactor: update docs to use new favicon and logo
  docs/poetry.lock
  docs/sphinx_scylladb_theme/header.html
  docs/sphinx_scylladb_theme/static/css/main.css
  docs/sphinx_scylladb_theme/static/img/logos/aerie-logo-dark.svg
  docs/sphinx_scylladb_theme/static/img/logos/aerie-logo-light.svg
  docs/sphinx_scylladb_theme/static/img/logos/aerie-wordmark-dark.svg
  docs/sphinx_scylladb_theme/static/img/logos/aerie-wordmark-light.svg
  docs/sphinx_scylladb_theme/static/img/logos/favicon.ico
  docs/sphinx_scylladb_theme/static/img/logos/favicon.svg
Labels: documentation

#398 docs: update command server Dockerfile and deployment readme
  command-expansion-server/.dockerignore
  command-expansion-server/Dockerfile.dev
  deployment/README.md
  docker-compose.yml
Labels: documentation

#378 Javadocs for merlin.protocol
  contrib/build.gradle
  examples/config-with-defaults/build.gradle
  examples/config-without-defaults/build.gradle
  examples/foo-missionmodel/build.gradle
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/MissionModelBuilder.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-framework/build.gradle
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/Context.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/InitializationContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/QueryContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ReplayingReactionContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/ThreadedReactionContext.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/resources/package-info.java
  merlin-framework/src/test/java/gov/nasa/jpl/aerie/merlin/framework/ThreadedTaskTest.java
  merlin-sdk/build.gradle
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/Initializer.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/Scheduler.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/Topic.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/driver/package-info.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/DirectiveType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/InputType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/MerlinPlugin.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/ModelType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/OutputType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/Resource.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/package-info.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/package-info.java
  scheduler/build.gradle
Labels: documentation

#404 [Aerie 2146] Include eDSL API docs on website
  .github/workflows/docs-pages.yaml
  .github/workflows/docs-pr.yml
  .gitignore
  docs/Makefile
  docs/buildExternalDocs.bash
  docs/poetry.lock
  docs/source/activity-plans/scheduling-guide.rst
  docs/source/conf.py
  docs/source/contribute/contribute-docs.rst
  docs/source/index.rst
  merlin-server/build.gradle
  merlin-server/constraints-dsl-compiler/package-lock.json
  merlin-server/constraints-dsl-compiler/package.json
  scheduler-server/build.gradle
  scheduler-server/scheduling-dsl-compiler/package-lock.json
  scheduler-server/scheduling-dsl-compiler/package.json
  scheduler-server/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
Labels: documentation

#380 [AERIE 2138] Plan Duplicate and Snapshots
  command-expansion-server/test/batchLoaders/simulatedActivityInstanceBatchLoader.spec.ts
  command-expansion-server/test/sequence-generation.spec.ts
  command-expansion-server/test/testUtils/ActivityDirective.ts
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/DatabaseTestHelper.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  deployment/hasura/metadata/databases/AerieMerlin/functions/functions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/hasura_functions_duplicate_plan_return_value.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/hasura_functions_get_plan_history_return_value.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_directive.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  deployment/hasura/metadata/databases/databases.yaml
  merlin-server/sql/merlin/hasura_functions.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/plan_collaboration.sql
  merlin-server/sql/merlin/tables/activity_directive.sql
  merlin-server/sql/merlin/tables/activity_directive_validations.sql
  merlin-server/sql/merlin/tables/plan.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/mocks/InMemoryMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ActivityDirective.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/MissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/UpdateActivityDirectiveValidationsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
Labels: breaking change

#407 [AERIE-2183] Revert name changes to boolean operations
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/And.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Not.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Or.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsersTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/SchedulingIntegrationTests.java
  scheduler/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java
  scheduler/src/test/java/gov/nasa/jpl/aerie/scheduler/AerieLanderRules.java
  scheduler/src/test/java/gov/nasa/jpl/aerie/scheduler/SimulationFacadeTest.java
  scheduler/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java
  scheduler/src/test/java/gov/nasa/jpl/aerie/scheduler/TestFilters.java
Labels: breaking change

#409 style: format command expansion server
  .git-blame-ignore-revs
  command-expansion-server/.prettierrc
  command-expansion-server/package.json
  command-expansion-server/src/app.ts
  command-expansion-server/src/common.ts
  command-expansion-server/src/db.ts
  command-expansion-server/src/defaultSeqBuilder.ts
  command-expansion-server/src/lib/codegen/ActivityTypescriptCodegen.ts
  command-expansion-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
  command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
  command-expansion-server/src/utils/temporalSerializers.ts
  command-expansion-server/src/worker.ts
  command-expansion-server/test/__snapshots__/command-types.spec.ts.snap
Labels: hotfix, style
