Repository NASA-AMMOS/aerie, pull requests merged in 2022-12, with the labels that each got.

#503 Bulk SeqJSON Actions
  deployment/hasura/metadata/actions.graphql
  deployment/hasura/metadata/actions.yaml
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/app.ts
  sequencing-server/test/activity-types.spec.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/Sequence.ts
  sequencing-server/test/testUtils/Simulation.ts
  sequencing-server/tsconfig.json
Labels: feature

#510 Ignore gaps outside of evaluation bounds for intospans
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/IntervalContainer.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Spans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Windows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/SpansFromWindows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/Split.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/time/WindowsTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
Labels: feature, scheduling, constraints

#508 Added the path param to schema types
  sequencing-server/src/lib/batchLoaders/activitySchemaBatchLoader.ts
  sequencing-server/src/lib/batchLoaders/simulatedActivityBatchLoader.ts
  sequencing-server/src/utils/assertions.ts
Labels: fix

#505 Add docs page on temporal subset scheduling
  docs/source/user-guide/ui-api-guide/scheduling/index.rst
  docs/source/user-guide/ui-api-guide/scheduling/temporal-subset-scheduling.rst
Labels: documentation

#527 Update Hasura from v2.12.0 to v2.12.1
  deployment/docker-compose.yml
  docker-compose.yml
  docker/Dockerfile.hasura
  e2e-tests/docker-compose-test.yml
Labels: hotfix, ci

#534 ci: temp fix NASA Scrub scan
  .github/workflows/codeql.yml
Labels: hotfix, ci, fix

#525 Fix infinite loop issue with recurrence goal and global scheduling condition + warning message
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: fix

#528 Plan Branch/Merge Docs
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/user-guide/ui-api-guide/api-examples.rst
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/approve_merge.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/begin_merge.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/cancel_merge.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/create_branch_dropdown.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/create_branch_modal.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/create_merge_rq.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/create_merge_rq_modal.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/deny_merge.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/open_branch_modal.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/open_branch_text.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/open_parent_plan.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/resolve_bulk.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/resolved_conflict.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/unresolved_conflict.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/view_incoming_merge_rqs.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/view_outgoing_merge_rqs.png
  docs/source/user-guide/ui-api-guide/images/plan_collaboration/withdraw_merge_rq.png
  docs/source/user-guide/ui-api-guide/plan-collaboration/index.rst
  docs/source/user-guide/ui-api-guide/plan-collaboration/merge-request.rst
Labels: documentation

#533 Make negative delays throw exceptions
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
Labels: fix

#520 Fix serialization of Duration to avoid rounding to millisecond
  e2e-tests/src/tests/simulation-microsecond-resolution.test.ts
  e2e-tests/src/types/simulation.d.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/ControllableDurationActivity.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/package-info.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/Duration.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfileSegmentsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PreparedStatements.java
Labels: hotfix, fix

#538 Fix Nasa Scrub in GitHub Actions
  .github/workflows/codeql.yml
Labels: hotfix, ci

#539 Added an override for qs to fix dependabot vulnerability
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: fix

#540 Update Gradle to 7.6
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#484 Include gaps in violations
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/Violation.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
Labels: feature

#545 Release Version 1.0.1
  docs/source/conf.py
  docs/source/user-guide/upgrade-guides/1-0-0-to-1-0-1.md
  docs/source/user-guide/upgrade-guides/index.rst
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#549 Run Prettier formatting over sequencing server
  .git-blame-ignore-revs
  sequencing-server/package.json
  sequencing-server/src/app.ts
  sequencing-server/test/activity-types.spec.ts
  sequencing-server/test/batchLoaders/expansionBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/simulatedActivityInstanceBatchLoader.spec.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/ActivityDirective.ts
  sequencing-server/test/testUtils/Expansion.ts
  sequencing-server/test/testUtils/MissionModel.ts
  sequencing-server/test/testUtils/Sequence.ts
  sequencing-server/test/testUtils/testUtils.ts
  sequencing-server/test/utils/temporalSerializers.spec.ts
Labels: style

#544 Add plan id and sim dataset id to seq JSON
  sequencing-server/.nvmrc
  sequencing-server/src/app.ts
  sequencing-server/src/defaultSeqBuilder.ts
  sequencing-server/src/lib/batchLoaders/simulatedActivityBatchLoader.ts
  sequencing-server/src/types/seqBuilder.ts
  sequencing-server/test/sequence-generation.spec.ts
Labels: feature

#507 Spans based scheduling basic AST
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/EvaluationEnvironment.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ForEachActivitySpans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ForEachActivityViolations.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/SpansAlias.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/RelativeActivityTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/timeexpressions/IntervalRelation.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/SpansGoal.java
Labels: feature, scheduling

#556 Remove default example UI views
  deployment/postgres-init-db/data/ui/views/example_0.json
  deployment/postgres-init-db/data/ui/views/example_1.json
  deployment/postgres-init-db/sql/ui/init.sql
Labels: breaking change, refactor

#553 Move Temporal.Duration to constraints eDSL
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/TypescriptCodeGenerationService.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  merlin-server/constraints-dsl-compiler/package-lock.json
  merlin-server/constraints-dsl-compiler/package.json
  merlin-server/constraints-dsl-compiler/src/libs/TemporalPolyfillTypes.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/constraints-dsl-compiler/src/libs/polyfills.ts
  merlin-server/constraints-dsl-compiler/src/main.ts
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GenerateConstraintsLibAction.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GenerateSchedulingLibAction.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/GenerateSchedulingLibActionTest.java
  scheduler-worker/scheduling-dsl-compiler/package-lock.json
  scheduler-worker/scheduling-dsl-compiler/package.json
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-ast.ts
  scheduler-worker/scheduling-dsl-compiler/src/main.ts
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java
Labels: feature, scheduling, constraints

#559 Fix SPICE not loading on M1 Docker images
  contrib/src/main/java/gov/nasa/jpl/aerie/spice/SpiceLoader.java
  contrib/src/main/resources/gov/nasa/jpl/aerie/spice/libJNISpice_Intel.so
  contrib/src/main/resources/gov/nasa/jpl/aerie/spice/libJNISpice_M1.so
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/Mission.java
Labels: fix
