Repository NASA-AMMOS/aerie, pull requests merged in 2023-05, with the labels that each got.

#902 Split Test Workflow into 2 Jobs
  .github/workflows/test.yml
Labels: ci, refactor

#880 Add Metadata Columns in DB
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_analysis.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/tables.yaml
  deployment/hasura/migrations/AerieMerlin/12_add_metadata/down.sql
  deployment/hasura/migrations/AerieMerlin/12_add_metadata/up.sql
  deployment/hasura/migrations/AerieScheduler/4_add_metadata/down.sql
  deployment/hasura/migrations/AerieScheduler/4_add_metadata/up.sql
  deployment/hasura/migrations/AerieScheduler/5_inline_scheduling_analysis/down.sql
  deployment/hasura/migrations/AerieScheduler/5_inline_scheduling_analysis/up.sql
  deployment/hasura/migrations/AerieSequencing/1_add_metadata/down.sql
  deployment/hasura/migrations/AerieSequencing/1_add_metadata/up.sql
  e2e-tests/src/types/constraint.d.ts
  e2e-tests/src/utilities/gql.ts
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/tables/activity_type.sql
  merlin-server/sql/merlin/tables/constraint.sql
  merlin-server/sql/merlin/tables/mission_model.sql
  merlin-server/sql/merlin/tables/plan.sql
  merlin-server/sql/merlin/tables/plan_collaborators.sql
  merlin-server/sql/merlin/tables/simulation_dataset.sql
  scheduler-server/sql/scheduler/applied_migrations.sql
  scheduler-server/sql/scheduler/init.sql
  scheduler-server/sql/scheduler/tables/scheduling_analysis.sql
  scheduler-server/sql/scheduler/tables/scheduling_goal.sql
  scheduler-server/sql/scheduler/tables/scheduling_goal_analysis.sql
  scheduler-server/sql/scheduler/tables/scheduling_goal_analysis_created_activities.sql
  scheduler-server/sql/scheduler/tables/scheduling_goal_analysis_satisfying_activities.sql
  scheduler-server/sql/scheduler/tables/scheduling_request.sql
  sequencing-server/sql/sequencing/applied_migrations.sql
  sequencing-server/sql/sequencing/tables/expansion_rule.sql
  sequencing-server/sql/sequencing/tables/expansion_set.sql
  sequencing-server/sql/sequencing/tables/expansion_set_to_rule.sql
  sequencing-server/sql/sequencing/tables/sequence.sql
Labels: feature, database

#849 Turn on JWT auth
  .env.template
  .github/workflows/test.yml
  deployment/.env
  deployment/Environment.md
  deployment/README.md
  deployment/docker-compose.yml
  deployment/kubernetes/aerie-gateway-deployment.yaml
  deployment/kubernetes/aerie-scheduler-deployment.yaml
  deployment/kubernetes/aerie-scheduler-worker-deployment.yaml
  deployment/kubernetes/aerie-sequencing-deployment.yaml
  deployment/kubernetes/aerie-ui-deployment.yaml
  deployment/kubernetes/hasura-deployment.yaml
  docker-compose.yml
  docs/DEVELOPER.md
  e2e-tests/docker-compose-test.yml
  e2e-tests/src/tests/scheduler.test.ts
  e2e-tests/src/utilities/requests.ts
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/SchedulerAppDriver.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/config/AppConfiguration.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/SchedulerWorkerAppDriver.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/WorkerAppConfiguration.java
  sequencing-server/jestGlobalSetup.js
  sequencing-server/src/app.ts
  sequencing-server/src/env.ts
  sequencing-server/test/activity-types.spec.ts
  sequencing-server/test/batchLoaders/activitySchemaBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/commandDictionaryTypescriptBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/expansionBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/expansionSetBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/simulatedActivityInstanceBatchLoader.spec.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/command-types.spec.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
Labels: breaking change, feature

#909 Fix constraint model by removing 'summary'
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/Constraint.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ConstraintRecord.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetModelConstraintsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetPlanConstraintsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
Labels: refactor

#915 Change severity scale for bug issue template
  .github/ISSUE_TEMPLATE/1-bug_report.yml
Labels: documentation

#899 Store expanded sequences
  .github/workflows/pgcmp.yml
  deployment/hasura/config.yaml
  deployment/hasura/metadata/databases/AerieSequencing/tables/public_expanded_sequences.yaml
  deployment/hasura/metadata/databases/AerieSequencing/tables/tables.yaml
  deployment/hasura/migrations/AerieSequencing/2_add_expanded_sequences/down.sql
  deployment/hasura/migrations/AerieSequencing/2_add_expanded_sequences/up.sql
  sequencing-server/sql/sequencing/applied_migrations.sql
  sequencing-server/sql/sequencing/init.sql
  sequencing-server/sql/sequencing/tables/expanded_sequences.sql
  sequencing-server/src/routes/command-expansion.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/testUtils/Expansion.ts
Labels: feature, sequencing, database

#918 Rename activity_type.category to activity_type.subsystem
  deployment/hasura/migrations/AerieMerlin/12_add_metadata/down.sql
  deployment/hasura/migrations/AerieMerlin/12_add_metadata/up.sql
  merlin-server/sql/merlin/tables/activity_type.sql
Labels: hotfix, fix, database

#923 Add additional Hasura metadata env vars
  deployment/Environment.md
  deployment/docker-compose.yml
  deployment/hasura/metadata/actions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml
  deployment/kubernetes/hasura-deployment.yaml
  docker-compose.yml
  e2e-tests/docker-compose-test.yml
Labels: refactor

#908 ParametricDuration annotation
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/DownloadBananaActivity.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/package-info.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/MissionModelParser.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/generator/MissionModelGenerator.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/metamodel/EffectModelRecord.java
  merlin-framework/src/main/java/gov/nasa/jpl/aerie/merlin/framework/annotations/ActivityType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/DurationType.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/ParametricDurationTest.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: performance, feature, scheduling

#911 Assign zero duration to activities with no effect model
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/generator/MissionModelGenerator.java
Labels: feature, scheduling

#939 Release v1.7.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#921 Add resource types table
  .github/scripts/compareDatabasesDown.sh
  .github/scripts/explanations
  .github/scripts/explanations_merlin_down
  .github/workflows/pgcmp.yml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_resource_type.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  deployment/hasura/migrations/AerieMerlin/13_resource_types/down.sql
  deployment/hasura/migrations/AerieMerlin/13_resource_types/up.sql
  e2e-tests/src/tests/mission-models.test.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/tables/resource_type.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/MissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/CreateActivityTypeAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/InsertActivityTypesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/InsertResourceTypesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/MissionModelService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubMissionModelService.java
Labels: performance, feature, database

#926 Add ACTIVE and LOAD to eDSL
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/command-expansion.spec.ts
Labels: feature, sequencing

#946 Help gradle find node for testing
  merlin-server/build.gradle
  scheduler-worker/build.gradle
Labels: build, fix

#942 Add parsed command dict db col
  deployment/hasura/metadata/actions.graphql
  deployment/hasura/migrations/AerieSequencing/4_add_parsed_json/down.sql
  deployment/hasura/migrations/AerieSequencing/4_add_parsed_json/up.sql
  sequencing-server/sql/sequencing/applied_migrations.sql
  sequencing-server/sql/sequencing/tables/command_dictionary.sql
  sequencing-server/src/app.ts
  sequencing-server/test/batchLoaders/expansionSetBatchLoader.spec.ts
  sequencing-server/test/command-dictionary.spec.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/command-types.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/CommandDictionary.ts
Labels: feature, sequencing, database

#931 Changed constraint violation api to return a list of violations rathe…
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/ConstraintType.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/Violation.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  deployment/hasura/metadata/actions.graphql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/mocks/InMemoryPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/Constraint.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/MissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/PlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalPlanService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/MissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/PlanService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubMissionModelService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubPlanService.java
Labels: breaking change, refactor, constraints

#960 Make `Description` optional across the DB
  deployment/hasura/migrations/AerieMerlin/15_defintion_consistency/down.sql
  deployment/hasura/migrations/AerieMerlin/15_defintion_consistency/up.sql
  deployment/hasura/migrations/AerieScheduler/7_definition_consistency/down.sql
  deployment/hasura/migrations/AerieScheduler/7_definition_consistency/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/tables/constraint.sql
  merlin-server/sql/merlin/tables/simulation_template.sql
  scheduler-server/sql/scheduler/applied_migrations.sql
  scheduler-server/sql/scheduler/tables/scheduling_condition.sql
  scheduler-server/sql/scheduler/tables/scheduling_goal.sql
Labels: fix, database
