Repository NASA-AMMOS/aerie, pull requests merged in 2023-01, with the labels that each got.

#569 Update package-lock.json
  sequencing-server/package-lock.json
Labels: build

#566 Add multi-arch image builds in `publish` workflow
  .github/workflows/publish.yml
Labels: ci

#576 Hotfix remove multi-arch builds
  .github/workflows/publish.yml
Labels: hotfix

#561 Governance Model Document Creation
  GOVERNANCE.md
Labels: documentation

#571 Add help links to README
  README.md
Labels: documentation

#580 Update readme with new doc link
  README.md
Labels: documentation

#584 Add QEMU and buildx action for multi-arch container images
  .github/workflows/publish.yml
Labels: ci

#582 Add schema_migrations table
  .gitignore
  deployment/hasura/migrations/.gitkeep
  deployment/hasura/migrations/AerieMerlin/0_create_schema_migrations/up.sql
  deployment/hasura/migrations/AerieScheduler/0_create_schema_migrations/up.sql
  deployment/hasura/migrations/AerieSequencing/0_create_schema_migrations/up.sql
  deployment/hasura/migrations/AerieUI/0_create_schema_migrations/up.sql
  deployment/postgres-init-db/sql/ui/applied_migrations.sql
  deployment/postgres-init-db/sql/ui/init.sql
  deployment/postgres-init-db/sql/ui/tables/schema_migrations.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/tables/schema_migrations.sql
  scheduler-server/sql/scheduler/applied_migrations.sql
  scheduler-server/sql/scheduler/init.sql
  scheduler-server/sql/scheduler/tables/schema_migrations.sql
  sequencing-server/sql/sequencing/applied_migrations.sql
  sequencing-server/sql/sequencing/init.sql
  sequencing-server/sql/sequencing/tables/schema_migrations.sql
Labels: feature, database

#585 Update Apache Commons BCEL to 6.6.0
  merlin-server/build.gradle
  merlin-worker/build.gradle
  scheduler-server/build.gradle
  scheduler-worker/build.gradle
Labels: build, security

#589 Remove testing from publish workflow
  .github/workflows/publish.yml
Labels: ci

#603 Move clearTable to DatabaseTestHelper
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/CommandExpansionDatabaseTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/DatabaseTestHelper.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/MerlinDatabaseTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/SchedulerDatabaseTests.java
Labels: refactor, test

#600 Update the all services to use Node LTS 18.0
  merlin-server/Dockerfile
  merlin-server/build.gradle
  scheduler-worker/Dockerfile
  scheduler-worker/build.gradle
  sequencing-server/.nvmrc
  sequencing-server/Dockerfile
  sequencing-server/Dockerfile.dev
  sequencing-server/build.gradle
  sequencing-server/package-lock.json
Labels: build

#606 Add Kubernetes manifests
  deployment/kubernetes/aerie-file-store-persistentvolumeclaim.yaml
  deployment/kubernetes/aerie-gateway-deployment.yaml
  deployment/kubernetes/aerie-gateway-service.yaml
  deployment/kubernetes/aerie-merlin-deployment.yaml
  deployment/kubernetes/aerie-merlin-service.yaml
  deployment/kubernetes/aerie-merlin-worker-deployment.yaml
  deployment/kubernetes/aerie-merlin-worker-service.yaml
  deployment/kubernetes/aerie-scheduler-deployment.yaml
  deployment/kubernetes/aerie-scheduler-service.yaml
  deployment/kubernetes/aerie-scheduler-worker-deployment.yaml
  deployment/kubernetes/aerie-scheduler-worker-service.yaml
  deployment/kubernetes/aerie-sequencing-deployment.yaml
  deployment/kubernetes/aerie-sequencing-service.yaml
  deployment/kubernetes/aerie-ui-deployment.yaml
  deployment/kubernetes/aerie-ui-ingress.yaml
  deployment/kubernetes/aerie-ui-service.yaml
  deployment/kubernetes/hasura-deployment.yaml
  deployment/kubernetes/hasura-service.yaml
  deployment/kubernetes/postgres-data-persistentvolumeclaim.yaml
  deployment/kubernetes/postgres-deployment.yaml
  deployment/kubernetes/postgres-service.yaml
Labels: ci

#615 Remove docs-links.yaml Workflow
  .github/workflows/docs-links.yaml
Labels: ci

#617 Fixed the ordered of repeat args in sequence generation
  sequencing-server/package-lock.json
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/src/utils/InheritedError.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/sequence-generation.spec.ts
Labels: fix

#616 Add JSON Spec to sequencing server
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/app.ts
  sequencing-server/src/defaultSeqBuilder.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/src/types/seqBuilder.ts
  sequencing-server/src/worker.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/sequence-generation.spec.ts
Labels: refactor, sequencing

#604 Catch long overflows when looking for intersection
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearEquation.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/model/LinearProfileTest.java
Labels: hotfix, fix

#619 Release Version 1.0.2
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#623 Cardinality goal does not respect applywhen
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/CardinalityGoal.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/PrioritySolverTest.java
Labels: fix, scheduling

#626 Increase Trivy timeout
  .github/workflows/publish.yml
Labels: ci
