Repository NASA-AMMOS/aerie, pull requests merged in 2023-07, with the labels that each got.

#1008 Return Tags in Hasura Plan Merge Functions
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  deployment/hasura/metadata/databases/AerieMerlin/tables/hasura_functions/get_conflicting_activities_return_value.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/hasura_functions/get_non_conflicting_activities_return_value.yaml
  deployment/hasura/migrations/AerieMerlin/18_get_tags_in_hasura_fns/down.sql
  deployment/hasura/migrations/AerieMerlin/18_get_tags_in_hasura_fns/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/functions/hasura/plan_merge_functions.sql
  merlin-server/sql/merlin/tables/metadata/activity_directive_tags.sql
  merlin-server/sql/merlin/tables/metadata/snapshot_activity_tags.sql
Labels: fix, database

#1007 Shift operation for profiles
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/DiscreteProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearProfile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/Profile.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Interval.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Windows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ActivityWindow.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/DiscreteParameter.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/DiscreteProfileFromDuration.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/EndOf.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ShiftBy.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ShiftWindowsEdges.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/StartOf.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/time/WindowsTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/tree/ASTTests.java
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/transformers/TransformerAfterEach.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/transformers/TransformerBeforeEach.java
Labels: feature, constraints

#1017 Update environment document
  deployment/Environment.md
Labels: documentation

#1013 Track constraint checking
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_constraint_run.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_simulation_dataset.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  deployment/hasura/migrations/AerieMerlin/20_constraint_run/down.sql
  deployment/hasura/migrations/AerieMerlin/20_constraint_run/up.sql
  e2e-tests/src/tests/constraints.test.ts
  e2e-tests/src/tests/external-datasets.test.ts
  e2e-tests/src/types/constraint.d.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/tables/constraint.sql
  merlin-server/sql/merlin/tables/constraint_run.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/AerieAppDriver.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/Constraint.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/SimulationResultsHandle.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/ConstraintRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/InMemoryResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ConstraintRunRecord.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetValidConstraintRunsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/InsertConstraintRunsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresConstraintRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresMissionModelRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalConstraintService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindingsTest.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubConstraintService.java
Labels: feature, constraints

#1024 Release v1.10.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1018 EPOCH HMS String Parsing should support Negative Duration
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/sequence-generation.spec.ts
Labels: bug, sequencing

#1028 Add aerie_admin role to Hasura action permissions
  deployment/hasura/metadata/actions.yaml
Labels: refactor

#1029 Fix Merge Function Volatility and Add Missing Select Permissions
  deployment/hasura/metadata/databases/AerieMerlin/functions/functions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan_snapshot.yaml
  deployment/hasura/migrations/AerieMerlin/21_user_role_permissions/up.sql
  merlin-server/sql/merlin/functions/hasura/plan_merge_functions.sql
Labels: fix

#1031 Add hasura relationship metadata for linking scheduling goals/conditions to scheduling specs
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_condition.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_goal.yaml
Labels: refactor

#1033 Remove Action Keys that Cannot Take Fine-Grained Permissions
  deployment/hasura/migrations/AerieMerlin/21_user_role_permissions/up.sql
  merlin-server/sql/merlin/domain-types/permissions.sql
Labels: refactor

#1035 Remove nonexistent keys from default permissions
  deployment/hasura/migrations/AerieMerlin/21_user_role_permissions/up.sql
  merlin-server/sql/merlin/tables/metadata/user_role_permission.sql
Labels: fix

#984 Add `getEffectiveArgumentsBulk` Hasura Action
  deployment/hasura/metadata/actions.graphql
  deployment/hasura/metadata/actions.yaml
  e2e-tests/src/tests/effective-arguments.test.ts
  e2e-tests/src/types/parameter.d.ts
  e2e-tests/src/utilities/gql.ts
  e2e-tests/src/utilities/requests.ts
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/HasuraParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/HasuraAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/MissionModelService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubMissionModelService.java
Labels: feature, simulation

#1032 Add Java Action Permissions
  README.md
  deployment/docker-compose.yml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_constraint_run.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_simulation.yaml
  docker-compose.yml
  e2e-tests/docker-compose-test.yml
  e2e-tests/src/tests/scheduler.test.ts
  e2e-tests/src/types/scheduling-goal.d.ts
  e2e-tests/src/utilities/requests.ts
  merlin-server/build.gradle
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/AerieAppDriver.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/config/AppConfiguration.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/LocalAppExceptionBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindingsTest.java
  permissions/build.gradle
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/Action.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/PermissionType.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/PermissionsService.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/PlanOwnerOrCollaborator.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/exceptions/ExceptionSerializers.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/exceptions/NoSuchPlanException.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/exceptions/NoSuchSchedulingSpecificationException.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/exceptions/PermissionsServiceException.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/exceptions/Unauthorized.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/gql/GraphQLPermissionsService.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/gql/PlanId.java
  permissions/src/main/java/gov/nasa/jpl/aerie/permissions/gql/SchedulingSpecificationId.java
  scheduler-server/build.gradle
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/SchedulerAppDriver.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/http/SchedulerBindings.java
  sequencing-server/test/testUtils/testUtils.ts
  settings.gradle
Labels: feature

#1030 Added permission checking to the sequencing server endpoints
  sequencing-server/jestGlobalSetup.js
  sequencing-server/src/app.ts
  sequencing-server/src/routes/command-expansion.ts
  sequencing-server/src/utils/hasura.ts
  sequencing-server/src/utils/helpers.ts
  sequencing-server/test/testUtils/testUtils.ts
Labels: feature, sequencing

#988 Fix recurrence goal bug that doesn't schedule goal if recurrence interval is greater than plan
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Problem.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/FixedDurationTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/LongDurationPlanTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/ParametricDurationTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/PrioritySolverTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/SimulationFacadeTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestCardinalityGoal.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestRecurrenceGoal.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestRecurrenceGoalExtended.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUnsatisfiableCompositeGoals.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/GoalBuilder.java
Labels: fix

#1039 Allow user role to update scheduling_specification.plan_revision
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_specification.yaml
Labels: fix

#1042 Release v1.11.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1043 Make claim actions respect `canceled` status
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ClaimSimulationAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/ClaimRequestAction.java
Labels: fix
