Repository NASA-AMMOS/aerie, pull requests merged in 2023-04, with the labels that each got.

#835 Use simulated id rather than directive id as key for simulatedActivityRecords
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
Labels: fix

#842 Various GH action workflow updates
  .github/workflows/codeql.yml
  .github/workflows/pgcmp.yml
  .github/workflows/pr.yml
  .github/workflows/publish.yml
  .github/workflows/security-scan.yml
  .github/workflows/test.yml
Labels: ci

#844 Add missing mark_migration_rolled_back
  deployment/hasura/migrations/AerieMerlin/7_store_sim_args_in_dataset/down.sql
Labels: hotfix, fix, database

#845 Update Aerie_DB_Migration
  .github/workflows/pgcmp.yml
  deployment/aerie_db_migration
  deployment/aerie_db_migration.py
  deployment/requirements.txt
Labels: fix

#875 Fix hardcoded command stem bug
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
Labels: hotfix, fix

#850 AutoValueMapper improvements
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/Configuration.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/Mission.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/ParameterTestActivity.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/RecordParameter.java
  examples/banananation/src/test/java/gov/nasa/jpl/aerie/banananation/SimulationUtility.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/AutoValueMappers.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/MissionModelParser.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/MissionModelProcessor.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/TypePattern.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/generator/MissionModelGenerator.java
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/metamodel/MissionModelRecord.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/SimulationUtility.java
Labels: feature, fix

#876 Expanded sequence sorting
  sequencing-server/src/defaultSeqBuilder.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/sequence-generation.spec.ts
Labels: feature, sequencing

#847 Allow for separation of activity matching from activity creation in scheduling eDSL
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/TypescriptCodeGenerationService.java
  merlin-server/constraints-dsl-compiler/src/libs/mission-model-generated-code.ts
  merlin-server/constraints-dsl-compiler/src/main.ts
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ConstraintsCompilationError.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/TypescriptCodeGenerationServiceTest.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/ActivityTemplateGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/CardinalityGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/CoexistenceGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/SerializedValueSubsetTest.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/SchedulingCompilationError.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/SchedulingDSL.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/GoalBuilder.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationService.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationServiceTest.java
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-ast.ts
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-mission-model-generated-code.ts
  scheduler-worker/scheduling-dsl-compiler/src/main.ts
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: feature, scheduling, clipper

#886 Release v1.5.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#888 Fix constraints codegen when there are no real resources
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/TypescriptCodeGenerationService.java
  examples/minimal-mission-model/build.gradle
  examples/minimal-mission-model/src/main/java/gov/nasa/jpl/aerie/minimalmissionmodel/Configuration.java
  examples/minimal-mission-model/src/main/java/gov/nasa/jpl/aerie/minimalmissionmodel/Mission.java
  examples/minimal-mission-model/src/main/java/gov/nasa/jpl/aerie/minimalmissionmodel/SingleActivity.java
  examples/minimal-mission-model/src/main/java/gov/nasa/jpl/aerie/minimalmissionmodel/package-info.java
  examples/minimal-mission-model/src/main/resources/META-INF/services/gov.nasa.jpl.aerie.merlin.protocol.model.MerlinPlugin
  examples/minimal-mission-model/src/main/resources/META-INF/services/gov.nasa.jpl.aerie.merlin.protocol.model.SchedulerPlugin
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/TypescriptCodeGenerationServiceTest.java
  scheduler-worker/build.gradle
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
  settings.gradle
Labels: bug, fix, scheduling

#889 Add GH issue templates for bugs and features
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug_report.yml
  .github/ISSUE_TEMPLATE/2-feature_request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#891 Use 'input' for issue template bug report version field
  .github/ISSUE_TEMPLATE/1-bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#893 FixedDuration handling bug
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: bug, fix

#890 Added Local and Parameters with TS 5
  merlin-server/constraints-dsl-compiler/package-lock.json
  merlin-server/constraints-dsl-compiler/package.json
  scheduler-worker/scheduling-dsl-compiler/package-lock.json
  scheduler-worker/scheduling-dsl-compiler/package.json
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/src/routes/seqjson.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/tsconfig.json
Labels: feature, sequencing
