Repository NASA-AMMOS/aerie, pull requests merged in 2023-06, with the labels that each got.

#948 Request eDSL
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
Labels: feature, sequencing

#964 Update postgres base image to 14.8
  deployment/docker-compose.yml
  docker-compose.yml
  docker/Dockerfile.postgres
  e2e-tests/docker-compose-test.yml
Labels: build, security

#966 Fix dynamics serialization in GraphQLMerlinService
  e2e-tests/src/tests/scheduler.test.ts
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
Labels: fix

#951 Fix enum types for scheduling eDSL presets
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationService.java
  scheduler-server/src/test/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationServiceTest.java
  scheduler-server/src/testFixtures/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationServiceTestFixtures.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java
Labels: fix

#973 Update env var docs with latest changes
  deployment/Environment.md
Labels: documentation

#970 Allow filtering forEach ActivityExpressions on activity arguments
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ForEachActivitySpans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/StructExpressionAt.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/GoalBuilder.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: feature, scheduling

#955 Set seq server owner fields
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/routes/command-expansion.ts
  sequencing-server/src/types/jwtAuthentication.ts
  sequencing-server/src/utils/helpers.ts
  sequencing-server/test/activity-types.spec.ts
  sequencing-server/test/batchLoaders/activitySchemaBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/commandDictionaryTypescriptBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/expansionBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/expansionSetBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/simulatedActivityInstanceBatchLoader.spec.ts
  sequencing-server/test/command-dictionary.spec.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/command-types.spec.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/CommandDictionary.js
  sequencing-server/test/testUtils/testUtils.ts
Labels: feature, sequencing

#947 Refactor rootfinding to simulate less and catch simulation exceptions
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/activities/LateRiserActivity.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/models/TimeTrackerDaemon.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/package-info.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationDriver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: performance, feature, fix, scheduling

#978 Release v1.8.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#979 Stop resumable simulation driver at end of horizon
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationDriver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationTest.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: fix, scheduling, clipper

#982 Add `PUBLIC_LOGIN_PAGE` to `aerie_ui`s env vars
  deployment/docker-compose.yml
  docker-compose.yml
Labels: ci

#985 Make Migration Script Return Non-Zero Exit Code
  deployment/aerie_db_migration.py
Labels: bug, ci

#980 Activate and load: remove addition properties
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
Labels: bug, fix, sequencing

#986 Update Sequencing package-lock.json
  sequencing-server/package-lock.json
Labels: ci

#993 Updated the developer docs for apple silicon
  docs/DEVELOPER.md
Labels: documentation

#992 Include dataset id in hasura relationship between profile and profile segment
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_profile.yaml
Labels: performance

#1000 Allow user to update model_id, plan_id of Constraints
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_constraint.yaml
Labels: fix

#1001 Declare default permissions for Hasura actions/functions
  deployment/hasura/metadata/actions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/functions/functions.yaml
  docker-compose.yml
Labels: refactor, database

#1009 Add `minus` helper function
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
Labels: feature, constraints

#1005 Add missing columns to hasura permissions
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_plan_dataset.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_span.yaml
  deployment/hasura/metadata/databases/AerieSequencing/tables/public_command_dictionary.yaml
  deployment/hasura/metadata/databases/AerieSequencing/tables/public_sequence.yaml
Labels: fix

#1011 Add optional name parameter to `createExpansionSet`
  deployment/hasura/metadata/actions.graphql
  sequencing-server/src/routes/command-expansion.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/testUtils/Expansion.ts
Labels: feature, sequencing, database
