Repository NASA-AMMOS/aerie, pull requests merged in 2023-02, with the labels that each got.

#598 Enable jacocoTestReport task for all java subprojects
  .github/workflows/test.yml
  constraints/build.gradle
  contrib/build.gradle
  db-tests/build.gradle
  examples/banananation/build.gradle
  examples/config-with-defaults/build.gradle
  examples/config-without-defaults/build.gradle
  examples/foo-missionmodel/build.gradle
  merlin-driver/build.gradle
  merlin-framework/build.gradle
  merlin-sdk/build.gradle
  merlin-server/build.gradle
  parsing-utilities/build.gradle
  scheduler-driver/build.gradle
  scheduler-server/build.gradle
  scheduler-worker/build.gradle
Labels: test

#634 Remove obsolete doc workflows
  .github/workflows/docs-pages.yaml
  .github/workflows/docs-pr.yml
Labels: ci

#639 Add new deploy to GH pages workflow
  .github/workflows/deploy-to-gh-pages.yml
  merlin-server/constraints-dsl-compiler/package-lock.json
  merlin-server/constraints-dsl-compiler/package.json
  scheduler-worker/scheduling-dsl-compiler/package-lock.json
  scheduler-worker/scheduling-dsl-compiler/package.json
Labels: ci

#647 Add Java docs to GitHub pages
  .github/workflows/deploy-to-gh-pages.yml
  build.gradle
Labels: ci

#649 Order deploy GH pages steps properly
  .github/workflows/deploy-to-gh-pages.yml
Labels: hotfix, ci

#602 Accumulated duration for windows/spans
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsers.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/model/LinearEquation.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Interval.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/IntervalContainer.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Spans.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/time/Windows.java
  constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/AccumulatedDuration.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/json/ConstraintParsersTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/time/SpansTest.java
  constraints/src/test/java/gov/nasa/jpl/aerie/constraints/time/WindowsTest.java
  merlin-server/constraints-dsl-compiler/src/libs/constraints-ast.ts
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/http/ActivityTemplateJsonParser.java
Labels: feature, constraints

#650 Cannot read field "durationInMicroseconds" because "right" is null
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/ActivityInstance.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: bug, fix

#656 Add back Aerie logo for README.md
  README.md
  docs/img/aerie-wordmark-with-background.svg
Labels: documentation

#658 Move contributing, move governance, update readme, update developer
  CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
  docs/DEVELOPER.md
  docs/GOVERNANCE.md
Labels: documentation

#654 Update all the sequencing server packages
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/app.ts
Labels: build, sequencing

#570 Anchors
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/AnchorTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/DatabaseTestHelper.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  deployment/hasura/metadata/databases/AerieMerlin/functions/functions.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_directive.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_anchor_validation_status.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  deployment/hasura/migrations/AerieMerlin/1_anchors/down.sql
  deployment/hasura/migrations/AerieMerlin/1_anchors/up.sql
  merlin-server/sql/merlin/hasura_functions.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/plan_collaboration.sql
  merlin-server/sql/merlin/plan_merge.sql
  merlin-server/sql/merlin/tables/activity_directive.sql
  merlin-server/sql/merlin/tables/anchor_validation_status.sql
Labels: feature, database

#645 Anchors in simulation
  examples/banananation/src/test/java/gov/nasa/jpl/aerie/banananation/SimulationUtility.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimulateMapSchedule.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/ActivityDirective.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/ActivityDirectiveId.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/ActivityInstanceId.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulatedActivity.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulatedActivityId.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResults.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/StartOffsetReducer.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/UnfinishedActivity.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-driver/src/test/java/gov/nasa/jpl/aerie/merlin/driver/AnchorSimulationTest.java
  merlin-driver/src/test/java/gov/nasa/jpl/aerie/merlin/driver/CellExpiryTest.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/exceptions/NoSuchActivityInstanceException.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinBindings.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/MerlinParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/mocks/InMemoryPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ActivityDirectiveForValidation.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ActivityInstance.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/NewPlan.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/Plan.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/PlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ActivityDirectiveRecord.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetActivityDirectivesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/CreateSimulationMessage.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/MissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/SynchronousSimulationAgent.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/Fixtures.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubMissionModelService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubPlanService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/remotes/PlanRepositoryContractTest.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationDriver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationTest.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/exceptions/NoSuchActivityInstanceException.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/MerlinPlan.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/GetCreatedActivitiesAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/GetSatisfyingActivitiesAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/InsertCreatedActivitiesAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/InsertSatisfyingActivitiesAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/remotes/postgres/PostgresResultsCellRepository.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/PlanService.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/ScheduleResults.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/MockMerlinService.java
Labels: breaking change, feature

#663 Anchors in Scheduling
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/ControllableDurationActivity.java
  examples/banananation/src/main/java/gov/nasa/jpl/aerie/banananation/activities/DurationParameterActivity.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/conflicts/MissingActivityInstanceConflict.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/conflicts/MissingAssociationConflict.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/TimeRangeExpression.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplateDisjunction.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpressionDisjunction.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/ActivityTemplateGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/CardinalityGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/CoexistenceGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/ProceduralCreationGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Plan.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/PlanInMemory.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingActivityDirective.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingActivityDirectiveId.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingActivityInstanceId.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/IncrementalSimulationDriver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationDriver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationFacade.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/Evaluation.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/optimizers/Optimizer.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/optimizers/OptimizerEarliestEndTime.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/optimizers/OptimizerLatestStartTime.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/AerieLanderRules.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/AerieLanderRulesTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/AerieLanderTestUtility.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/LongDurationPlanTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/PrioritySolverTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/SimulationFacadeTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestCardinalityGoal.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/AnchorSchedulerTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationTest.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/MerlinActivityInstance.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/MerlinPlan.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/PlanService.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SynchronousSchedulerAgent.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/MockMerlinService.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: feature, scheduling

#671 Fix `SchedulingActivityDirective.instantiateArguments()`
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingActivityDirective.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/InstantiateArgumentsTest.java
Labels: bug, fix

#670 Release v1.1.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#664 Add command interface to steps
  deployment/hasura/metadata/actions.graphql
  sequencing-server/src/app.ts
  sequencing-server/src/defaultSeqBuilder.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/worker.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/Sequence.ts
Labels: DON'T MERGE, breaking change, refactor, sequencing

#682 Correct AerieMerlin's "Current" Migration
  merlin-server/sql/merlin/applied_migrations.sql
Labels: hotfix, fix, database

#672 Added handling for activities that stretch past a plans duration
  sequencing-server/src/app.ts
  sequencing-server/src/lib/batchLoaders/simulatedActivityBatchLoader.ts
  sequencing-server/test/sequence-generation.spec.ts
Labels: bug, sequencing

#690 Implement `negate` as wrapper of `times(-1)`
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationServiceTests.java
Labels: feature, constraints

#684 Fix Scheduling Dropping Daemons
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/Mission.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/activities/DaemonCheckerActivity.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/models/TimeTrackerDaemon.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/package-info.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationDriver.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
Labels: bug, fix, scheduling

#688 Validate seq json file upload
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/src/app.ts
  sequencing-server/test/seqjson-to-edsl.spec.ts
  sequencing-server/tsconfig.json
Labels: feature

#661 Minimize locks acquired for dataset partitions
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/MerlinDatabaseTests.java
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_dataset.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_profile.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_topic.yaml
  deployment/hasura/migrations/AerieMerlin/2_drop_profile_topic_fks/down.sql
  deployment/hasura/migrations/AerieMerlin/2_drop_profile_topic_fks/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/tables/dataset.sql
  merlin-server/sql/merlin/tables/event.sql
  merlin-server/sql/merlin/tables/profile.sql
  merlin-server/sql/merlin/tables/profile_segment.sql
  merlin-server/sql/merlin/tables/span.sql
  merlin-server/sql/merlin/tables/topic.sql
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/CreateDatasetPartitionsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/CreateEventPartitionAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/CreateProfileSegmentPartitionAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/CreateSpanPartitionAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresPlanRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
Labels: performance, fix

#696 Added a fix for when an activity type has the same name as a command
  sequencing-server/cdict/command_banananation.xml
  sequencing-server/src/lib/codegen/ActivityTypescriptCodegen.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/sequence-generation.spec.ts
Labels: bug, fix

#695 Activity Presets DB
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/AnchorTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PresetTests.java
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_directive.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_presets.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_activity_type.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_preset_to_directive.yaml
  deployment/hasura/metadata/databases/AerieMerlin/tables/tables.yaml
  deployment/hasura/migrations/AerieMerlin/3_activity_presets/down.sql
  deployment/hasura/migrations/AerieMerlin/3_activity_presets/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/hasura_functions.sql
  merlin-server/sql/merlin/init.sql
  merlin-server/sql/merlin/plan_collaboration.sql
  merlin-server/sql/merlin/plan_merge.sql
  merlin-server/sql/merlin/tables/activity_presets.sql
Labels: feature, database
