Repository NASA-AMMOS/aerie, pull requests merged in 2024-11, with the labels that each got.

#1586 Fix analysis mode of scheduling engine
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
Labels: fix

#1587 Switch semantics of filterLongerThan and filterShorterThan
  procedural/timeline/src/main/kotlin/gov/nasa/ammos/aerie/procedural/timeline/ops/GeneralOps.kt
Labels: breaking change

#1593 Release v3.1.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1605 Release v3.1.1
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
  stateless-aerie/src/main/java/gov/nasa/jpl/aerie/stateless/Main.java
Labels: release

#1607 Rename 'foo-procedures' to 'banana-procedures'
  procedural/examples/banana-procedures/README.md
  procedural/examples/banana-procedures/build.gradle
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/Helper.java
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/constraints/ConstFruit.java
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/package-info.java
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/procedures/SampleProcedure.java
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/procedures/SimulationDemo.java
  procedural/examples/banana-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/procedures/StayWellFed.java
  procedural/examples/banana-procedures/src/test/java/gov/nasa/ammos/aerie/procedural/examples/bananaprocedures/constraints/ProcedureLoader.java
  procedural/examples/foo-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/fooprocedures/constraints/Hello.java
  settings.gradle
Labels: refactor

#1608 Release v3.0.1
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
  stateless-aerie/src/main/java/gov/nasa/jpl/aerie/stateless/Main.java
Labels: release
