Repository NASA-AMMOS/aerie, pull requests merged in 2024-04, with the labels that each got.

#1384 Release v2.7.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1389 Release v2.6.99
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1391 Release v2.6.100
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1396 Allow Users to write to Model Scheduling Spec's `priority` Column
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_model_specification_goals.yaml
Labels: fix

#1386 Add Hasura relationship between Mission Model and Scheduling Specification
  deployment/hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml
Labels: fix

#1385 Return the Executing Directive Id in Simulation Error Response
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/SimulationTests.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/GQL.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/HasuraRequests.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/Configuration.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/Mission.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/activities/DaemonCheckerSpawner.java
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/package-info.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationException.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SpanException.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/SynchronousSimulationAgent.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationDriver.java
Labels: feature, simulation

#1401 Fix Id Sequences on Constraint, Goals, and Conditions
  deployment/hasura/migrations/AerieMerlin/39_update_constraints_sequence/down.sql
  deployment/hasura/migrations/AerieMerlin/39_update_constraints_sequence/up.sql
  deployment/hasura/migrations/AerieScheduler/14_update_scheduling_sequences/down.sql
  deployment/hasura/migrations/AerieScheduler/14_update_scheduling_sequences/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  scheduler-server/sql/scheduler/applied_migrations.sql
Labels: fix

#1404 Release v2.6.2
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1399 Update node to LTS (20)
  merlin-server/Dockerfile
  merlin-server/build.gradle
  scheduler-worker/Dockerfile
  scheduler-worker/build.gradle
Labels: build

#1406 Release v2.7.1
  e2e-tests/docker-compose-test.yml
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1407 Add Missing `merlin` Prefix
  db-tests/build.gradle
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/DatabaseTestHelper.java
  deployment/.env
  deployment/Environment.md
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/UpdateSimulationConfigurationRevisionAction.java
Labels: fix

#1408 Provide default DB usernames in `.env.template`
  .env.template
Labels: ci

#1410 Add "order by" when populating a plan spec
  deployment/merge_aerie_db/merge_db/migrate_scheduler_triggers.sql
  deployment/postgres-init-db/sql/tables/scheduler/scheduling_specification/scheduling_specification.sql
Labels: fix

#1409 Update Python requirements to Latest Versions
  deployment/merge_aerie_db/drop_old_dbs.sh
  deployment/merge_aerie_db/merge_db.sh
  deployment/requirements.txt
Labels: ci, fix

#1411 Release v2.8.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1418 Add Hasura Events Views
  .github/workflows/pgcmp.yml
  deployment/aerie_db_migration.py
  deployment/hasura/metadata/databases/tables/hasura/refresh_activity_type_logs.yaml
  deployment/hasura/metadata/databases/tables/hasura/refresh_model_parameter_logs.yaml
  deployment/hasura/metadata/databases/tables/hasura/refresh_resource_types_logs.yaml
  deployment/hasura/metadata/databases/tables/merlin/mission_model.yaml
  deployment/hasura/metadata/databases/tables/tables.yaml
  deployment/hasura/migrations/Aerie/1_hasura_events_views/down.sql
  deployment/hasura/migrations/Aerie/1_hasura_events_views/up.sql
  deployment/postgres-init-db/sql/applied_migrations.sql
  deployment/postgres-init-db/sql/init_hasura.sql
  deployment/postgres-init-db/sql/views/hasura/hasura_event_logs.sql
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/MissionModelTests.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/SchedulingTests.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/ModelEventLogs.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/GQL.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/HasuraRequests.java
Labels: feature, database, hasura

#1428 Release v2.6.102
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1412 Update to Postgres 16.2
  .github/workflows/pgcmp.yml
  deployment/docker-compose.yml
  docker-compose.yml
  docker/Dockerfile.postgres
  e2e-tests/docker-compose-many-workers.yml
  e2e-tests/docker-compose-test.yml
Labels: ci, refactor, database

#1432 Release v2.9.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release
