Repository NASA-AMMOS/aerie, pull requests merged in 2024-07, with the labels that each got.

#1493 E2E Tests: Provide Auth Header when Uploading Model JAR
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/GatewayRequests.java
  sequencing-server/test/testUtils/MissionModel.ts
Labels: test

#1502 Release v2.15.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1495 Span to Event Traceability
  deployment/hasura/metadata/databases/tables/merlin/dataset/span.yaml
  deployment/hasura/metadata/databases/tables/sequencing/activity_instance_commands.yaml
  deployment/hasura/migrations/Aerie/8_span_event_linkage/down.sql
  deployment/hasura/migrations/Aerie/8_span_event_linkage/up.sql
  deployment/postgres-init-db/sql/applied_migrations.sql
  deployment/postgres-init-db/sql/tables/merlin/dataset/event.sql
  deployment/postgres-init-db/sql/tables/merlin/dataset/span.sql
  deployment/postgres-init-db/sql/views/merlin/simulated_activity.sql
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/GQL.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResults.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/EventRecord.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetSimulationEventsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetSpanRecords.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/InsertSimulationEventsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostSpansAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/UpdateSimulatedActivityParentsAction.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
  sequencing-server/src/lib/batchLoaders/simulatedActivityBatchLoader.ts
Labels: simulation

#1511 Make Scheduler containers use the correct Envvar
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/SchedulerAppDriver.java
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/SchedulerWorkerAppDriver.java
Labels: breaking change

#1507 Stream Simulation Resources
  examples/foo-missionmodel/src/main/java/gov/nasa/jpl/aerie/foomissionmodel/models/TimeTrackerDaemon.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/FooSimulationDuplicationTest.java
  examples/foo-missionmodel/src/test/java/gov/nasa/jpl/aerie/foomissionmodel/SimulateMapSchedule.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/CachedEngineStore.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/CachedSimulationEngine.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/CheckpointSimulationDriver.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResults.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationResultsComputerInputs.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/Profile.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/ProfilingState.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/InMemorySimulationResourceManager.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/ResourceProfile.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/ResourceProfiles.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/ResourceSegments.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/SimulationResourceManager.java
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/resources/StreamingSimulationResourceManager.java
  merlin-driver/src/test/java/gov/nasa/jpl/aerie/merlin/driver/CellExpiryTest.java
  merlin-driver/src/test/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDuplicationTest.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ProfileParsers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/models/ProfileSet.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/InMemoryResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostProfilesAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/ProfileRepository.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/MissionModelService.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/SimulationAgent.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/SynchronousSimulationAgent.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ThreadedSimulationAgent.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/UncachedSimulationService.java
  merlin-server/src/test/java/gov/nasa/jpl/aerie/merlin/server/mocks/StubMissionModelService.java
  merlin-worker/src/main/java/gov/nasa/jpl/aerie/merlin/worker/MerlinWorkerAppDriver.java
  merlin-worker/src/main/java/gov/nasa/jpl/aerie/merlin/worker/postgres/PostgresProfileStreamer.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/CheckpointSimulationFacade.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/InMemoryCachedEngineStore.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationResultsConverter.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/AnchorSchedulerTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/CheckpointSimulationFacadeTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/InMemoryCachedEngineStoreTest.java
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/SimulationResultsComparisonUtils.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/ProfileSet.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/UnwrappedProfileSet.java
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinService.java
Labels: refactor, feature, simulation

#1517 Release v2.16.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1521 Release v2.11.2
  e2e-tests/docker-compose-many-workers.yml
  e2e-tests/docker-compose-test.yml
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1522 Release v2.11.2
  gradle.properties
Labels: release

#1523 Release v2.11.2
  gradle.properties
  sequencing-server/package.json
Labels: release
