Repository NASA-AMMOS/aerie, pull requests merged in 2024-09, with the labels that each got.

#1543 Update Postgres 16.2 -> 16.4
  .github/workflows/pgcmp.yml
  deployment/docker-compose.yml
  docker-compose.yml
  docker/Dockerfile.postgres
  e2e-tests/docker-compose-many-workers.yml
  e2e-tests/docker-compose-test.yml
Labels: publish

#1544 Hook workspace fk up to the correct table in migration
  deployment/hasura/migrations/Aerie/9_sequence_workspaces/up.sql
Labels: fix, database

#1545 Fix pgcmp workflow
  .github/scripts/compareDatabasesUp.sh
  .github/workflows/pgcmp.yml
Labels: ci

#1546 Add trivyignore file to ignore false positive CVEs in security scan
  .github/config/.trivyignore
  .github/workflows/publish.yml
Labels: publish

#1555 Release v2.19.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1559 Generator Constraints and Violation Messages
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/TimelineRemoteTests.java
  procedural/constraints/src/main/kotlin/gov/nasa/ammos/aerie/procedural/constraints/Constraint.kt
  procedural/constraints/src/main/kotlin/gov/nasa/ammos/aerie/procedural/constraints/GeneratorConstraint.kt
  procedural/constraints/src/main/kotlin/gov/nasa/ammos/aerie/procedural/constraints/Violation.kt
  procedural/constraints/src/main/kotlin/gov/nasa/ammos/aerie/procedural/constraints/Violations.kt
  procedural/constraints/src/test/kotlin/gov/nasa/ammos/aerie/procedural/constraints/GeneratorTest.kt
  procedural/constraints/src/test/kotlin/gov/nasa/ammos/aerie/procedural/constraints/NotImplementedPlan.kt
  procedural/constraints/src/test/kotlin/gov/nasa/ammos/aerie/procedural/constraints/NotImplementedSimulationResults.kt
  procedural/examples/foo-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/fooprocedures/constraints/ConstFruit.java
Labels: constraints

#1564 Release v2.20.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release
