Repository NASA-AMMOS/aerie, pull requests merged in 2024-02, with the labels that each got.

#1319 Release v2.3.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1237 Update JDK/JRE + Gradle
  constraints/build.gradle
  contrib/build.gradle
  db-tests/build.gradle
  docs/DEVELOPER.md
  e2e-tests/build.gradle
  examples/banananation/build.gradle
  examples/config-with-defaults/build.gradle
  examples/config-without-defaults/build.gradle
  examples/foo-missionmodel/build.gradle
  examples/minimal-mission-model/build.gradle
  examples/streamline-demo/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  merlin-driver/build.gradle
  merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java
  merlin-framework-junit/build.gradle
  merlin-framework-processor/build.gradle
  merlin-framework/build.gradle
  merlin-sdk/build.gradle
  merlin-server/Dockerfile
  merlin-server/build.gradle
  merlin-worker/Dockerfile
  merlin-worker/build.gradle
  parsing-utilities/build.gradle
  permissions/build.gradle
  scheduler-driver/build.gradle
  scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/simulation/ResumableSimulationTest.java
  scheduler-server/Dockerfile
  scheduler-server/build.gradle
  scheduler-worker/Dockerfile
  scheduler-worker/build.gradle
Labels: build, clipper-launch

#1338 Release v2.4.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1341 Update Java version to 21 in CI
  .github/workflows/create_jnispice.yml
  .github/workflows/deploy-to-gh-pages.yml
  .github/workflows/load-test.yml
  .github/workflows/publish.yml
  .github/workflows/security-scan.yml
  .github/workflows/test.yml
Labels: build, ci

#1345 Update pgjdbc to fix SQL injection vuln
  db-tests/build.gradle
  merlin-server/build.gradle
  merlin-worker/build.gradle
  scheduler-server/build.gradle
  scheduler-worker/build.gradle
Labels: database, security

#1339 Update GH Action Versions used in Workflows
  .github/workflows/cloc.yml
  .github/workflows/create_jnispice.yml
  .github/workflows/deploy-to-gh-pages.yml
  .github/workflows/load-test.yml
  .github/workflows/pgcmp.yml
  .github/workflows/publish.yml
  .github/workflows/security-scan.yml
  .github/workflows/test.yml
  load-tests/src/db-lockup-test.ts
Labels: ci

#1324 Improve large expansion sets
  docker-compose.yml
  sequencing-server/src/app.ts
  sequencing-server/src/env.ts
  sequencing-server/src/routes/command-expansion.ts
  sequencing-server/src/utils/PromiseThrottler.ts
  sequencing-server/src/worker.ts
Labels: feature, fix, sequencing

#1351 Update JNISpice Jar to JDK 21-compiled version
  third-party/JNISpice-N0067.jar
Labels: ci
