Repository NASA-AMMOS/aerie, pull requests merged in 2024-10, with the labels that each got.

#1568 Save activity names from procedural goals
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/SchedulingTests.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/Plan.java
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/GQL.java
  procedural/examples/foo-procedures/src/main/java/gov/nasa/ammos/aerie/procedural/examples/fooprocedures/procedures/SampleProcedure.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/SchedulingActivity.java
  scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/solver/PrioritySolver.java
  scheduler-driver/src/main/kotlin/gov/nasa/jpl/aerie/scheduler/plan/InMemoryEditablePlan.kt
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/GraphQLMerlinDatabaseService.java
Labels: fix, scheduling

#1575 Release v2.21.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1542 FPrime Dictionary Support
  deployment/docker-compose.yml
  deployment/hasura/metadata/actions.graphql
  docker-compose.yml
  sequencing-server/jest.config.js
  sequencing-server/package-lock.json
  sequencing-server/package.json
  sequencing-server/plugins/ampcs-dictionary-parser/package.json
  sequencing-server/plugins/ampcs-dictionary-parser/rollup.config.js
  sequencing-server/plugins/ampcs-dictionary-parser/src/ampcs-parser.ts
  sequencing-server/plugins/ampcs-dictionary-parser/tsconfig.json
  sequencing-server/plugins/fprime-dictionary-parser/package.json
  sequencing-server/plugins/fprime-dictionary-parser/rollup.config.js
  sequencing-server/plugins/fprime-dictionary-parser/schema/fprime-schema.json
  sequencing-server/plugins/fprime-dictionary-parser/schema/fprime-types.ts
  sequencing-server/plugins/fprime-dictionary-parser/src/fprime-parser.ts
  sequencing-server/plugins/fprime-dictionary-parser/test/dictionary/RefTopologyDictionary.json
  sequencing-server/plugins/fprime-dictionary-parser/test/test.ts
  sequencing-server/plugins/fprime-dictionary-parser/tsconfig.json
  sequencing-server/src/app.ts
  sequencing-server/src/env.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/src/utils/PluginManager.ts
  sequencing-server/test/batchLoaders/expansionBatchLoader.spec.ts
  sequencing-server/test/batchLoaders/expansionSetBatchLoader.spec.ts
  sequencing-server/test/command-expansion.spec.ts
  sequencing-server/test/command-types.spec.ts
  sequencing-server/test/db-state.spec.ts
  sequencing-server/test/dictionary.spec.ts
  sequencing-server/test/sequence-generation.spec.ts
  sequencing-server/test/testUtils/Dictionary.ts
Labels: publish

#1584 Release v3.0.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release
