Repository NASA-AMMOS/aerie, pull requests merged in 2024-05, with the labels that each got.

#1433 Enable expansion again
  sequencing-server/sql/sequencing/tables/expansion_set.sql
Labels: phoenix

#1435 Fix Delete trigger for v2.6.3
  .github/scripts/explanations
  .github/scripts/explanations_merlin_down
  db-tests/build.gradle
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/DatabaseTestHelper.java
  deployment/hasura/migrations/AerieScheduler/15_scheduling_goals_bulk_delete/down.sql
  deployment/hasura/migrations/AerieScheduler/15_scheduling_goals_bulk_delete/up.sql
  e2e-tests/docker-compose-test.yml
  scheduler-server/sql/scheduler/applied_migrations.sql
  scheduler-server/sql/scheduler/tables/scheduling_model_specification_goals.sql
  scheduler-server/sql/scheduler/tables/scheduling_specification_goals.sql
Labels: fix, scheduling, database

#1438 Release v2.6.3
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1431 Upload User SeqJson to database
  deployment/hasura/metadata/databases/AerieSequencing/tables/public_user_sequence.yaml
  sequencing-server/sql/sequencing/tables/user_sequence.sql
Labels: phoenix

#1436 Fix Scheduling Spec Goals Delete (for develop)
  .github/workflows/pgcmp.yml
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/SchedulerDatabaseTests.java
  deployment/hasura/migrations/Aerie/2_scheduling_goals_bulk_delete/down.sql
  deployment/hasura/migrations/Aerie/2_scheduling_goals_bulk_delete/up.sql
  deployment/postgres-init-db/sql/applied_migrations.sql
  deployment/postgres-init-db/sql/tables/scheduler/scheduling_specification/scheduling_model_specification_goals.sql
  deployment/postgres-init-db/sql/tables/scheduler/scheduling_specification/scheduling_specification_goals.sql
Labels: fix, scheduling, database

#1427 Quiet down successful builds
  constraints/build.gradle
  contrib/build.gradle
  contrib/src/main/java/gov/nasa/jpl/aerie/contrib/streamline/modeling/polynomial/PolynomialResources.java
  db-tests/build.gradle
  e2e-tests/build.gradle
  examples/banananation/build.gradle
  examples/config-with-defaults/build.gradle
  examples/config-without-defaults/build.gradle
  examples/foo-missionmodel/build.gradle
  examples/minimal-mission-model/build.gradle
  examples/streamline-demo/build.gradle
  merlin-driver/build.gradle
  merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/MissionModelProcessor.java
  merlin-framework/build.gradle
  merlin-sdk/build.gradle
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/DirectiveType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/model/InputType.java
  merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/package-info.java
  merlin-server/build.gradle
  merlin-server/constraints-dsl-compiler/package.json
  merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/Fallible.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintsDSLCompilationService.java
  parsing-utilities/build.gradle
  procedural/constraints/build.gradle
  procedural/timeline/build.gradle
  scheduler-driver/build.gradle
  scheduler-server/build.gradle
  scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/models/SchedulingDSL.java
  scheduler-worker/build.gradle
  scheduler-worker/scheduling-dsl-compiler/package.json
  scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
  scheduler-worker/src/main/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationService.java
  scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingIntegrationTests.java
  sequencing-server/build.gradle
  sequencing-server/tsconfig.json
Labels: build

#1442 Add DB Tests for Merging Sibling Plans
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
Labels: test

#1443 Write parents unfinished spans
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/SimulationTests.java
  merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/PostgresResultsCellRepository.java
Labels: fix

#1447 Release v2.10.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1450 Release v2.11.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1456 Update Docker-Compose for the Sequencing Server
  deployment/docker-compose.yml
  docker-compose.yml
Labels: ci

#1460 Release v2.12.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release
