Repository NASA-AMMOS/aerie, pull requests merged in 2024-01, with the labels that each got.

#1272 Add Scheduler Hasura Relationships
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_condition.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_goal.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_goal_analysis.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_goal_analysis_created_activities.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_goal_analysis_satisfying_activities.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_request.yaml
  deployment/hasura/metadata/databases/AerieScheduler/tables/public_scheduling_specification.yaml
Labels: hasura

#1261 Support JPL CoreFSW Variable References
  sequencing-server/src/lib/codegen/CommandEDSLPreface.spec.ts
  sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
  sequencing-server/src/lib/codegen/CommandTypeCodegen.ts
  sequencing-server/test/__snapshots__/command-types.spec.ts.snap
  sequencing-server/test/seqjson-to-edsl.spec.ts
Labels: feature, sequencing, clipper

#1284 Release v2.2.1
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1291 Release v2.2.1
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
Labels: release

#1292 Track when Merge Requests were last updated
  deployment/hasura/migrations/AerieMerlin/36_metadata_updated_at/down.sql
  deployment/hasura/migrations/AerieMerlin/36_metadata_updated_at/up.sql
  merlin-server/sql/merlin/applied_migrations.sql
  merlin-server/sql/merlin/tables/merge_request.sql
Labels: database
