Repository NASA-AMMOS/aerie, pull requests merged in 2025-04, with the labels that each got.

#1666 Disable on-update triggers during Procedural Constraint's Migration
  deployment/hasura/migrations/Aerie/16_procedural_constraints/up.sql
Labels: fix, database

#1667 Disable on-update triggers much more aggressively during Proc Constraints Migration
  deployment/hasura/migrations/Aerie/16_procedural_constraints/up.sql
Labels: fix, database

#1670 ignore DoS vulnerability CVE-2023-7272 in Trivy scans
  .github/config/.trivyignore
Labels: publish

#1641 Add Ability to Lock User Sequences
  db-tests/src/test/java/gov/nasa/jpl/aerie/database/UserSequenceTests.java
  deployment/hasura/metadata/databases/tables/sequencing/user_sequence.yaml
  deployment/hasura/migrations/Aerie/17_user_sequence_readonly/down.sql
  deployment/hasura/migrations/Aerie/17_user_sequence_readonly/up.sql
  deployment/postgres-init-db/sql/applied_migrations.sql
  deployment/postgres-init-db/sql/tables/sequencing/user_sequence.sql
Labels: sequencing, database, publish

#1674 Release v3.4.0
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
  stateless-aerie/src/main/java/gov/nasa/jpl/aerie/stateless/Main.java
Labels: release
