Repository NASA-AMMOS/aerie, pull requests merged in 2025-03, with the labels that each got.

#1640 Bugfix: Allow resource streaming jobs to finish before closing connections
  merlin-worker/src/main/java/gov/nasa/jpl/aerie/merlin/worker/postgres/PostgresProfileStreamer.java
Labels: fix

#1651 Release v3.3.1
  gradle.properties
  sequencing-server/package-lock.json
  sequencing-server/package.json
  stateless-aerie/src/main/java/gov/nasa/jpl/aerie/stateless/Main.java
Labels: release

#1634 Aerie Actions Backend - WIP
  .github/workflows/publish.yml
  action-server/.nvmrc
  action-server/.prettierignore
  action-server/.prettierrc.json
  action-server/Dockerfile
  action-server/Dockerfile.dev
  action-server/build.gradle
  action-server/eslint.config.mjs
  action-server/package-lock.json
  action-server/package.json
  action-server/src/app.ts
  action-server/src/config.ts
  action-server/src/db.ts
  action-server/src/listeners/dbListeners.ts
  action-server/src/middleware.ts
  action-server/src/threads/worker.ts
  action-server/src/threads/workerPool.ts
  action-server/src/type/types.ts
  action-server/src/utils/codeRunner.ts
  action-server/src/utils/logger.ts
  action-server/src/utils/validators.ts
  action-server/tests/codeRunner.test.ts
  action-server/tsconfig.json
  deployment/docker-compose.yml
  deployment/hasura/metadata/databases/tables/actions/action_definition.yaml
  deployment/hasura/metadata/databases/tables/actions/action_run.yaml
  deployment/hasura/metadata/databases/tables/tables.yaml
  deployment/hasura/migrations/Aerie/15_actions/down.sql
  deployment/hasura/migrations/Aerie/15_actions/up.sql
  deployment/kubernetes/aerie-action-deployment.yaml
  deployment/kubernetes/aerie-action-service.yaml
  deployment/postgres-init-db/sql/applied_migrations.sql
  deployment/postgres-init-db/sql/init.sql
  deployment/postgres-init-db/sql/init_actions.sql
  deployment/postgres-init-db/sql/init_db_users.sql
  deployment/postgres-init-db/sql/schemas.sql
  deployment/postgres-init-db/sql/tables/actions/action_definition.sql
  deployment/postgres-init-db/sql/tables/actions/action_run.sql
  deployment/proxy/docker-compose-proxy.yml
  docker-compose.yml
  e2e-tests/docker-compose-many-workers.yml
  e2e-tests/docker-compose-test.yml
  e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/utils/BaseURL.java
  sequencing-server/src/env.ts
  settings.gradle
Labels: publish, action
